project_id = "dhijrvssbudlnhgtcpyo"

[functions.funnel-optimizer]
  verify_jwt = true
  [functions.funnel-optimizer.cors]
    allowed_origins = ["*"]
    allowed_methods = ["POST", "OPTIONS", "GET"]
    allowed_headers = ["authorization", "x-client-info", "apikey", "content-type", "x-api-key"]