project_id = "dhijrvssbudlnhgtcpyo"

[functions.funnel-optimizer]
verify_jwt = true
  [functions.funnel-optimizer.cors]
    allowed_origins = ["http://localhost:8080", "https://*.webcontainer-api.io", "https://*.local-credentialless.webcontainer-api.io"]
    allowed_methods = ["POST", "OPTIONS", "GET"]
    allowed_headers = ["authorization", "x-client-info", "apikey", "content-type", "x-api-key"]